name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }]  # Corre cada hora
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AbyZerimar11
          base: header, activity, community, repositories
          config_timezone: America/Mexico_City
          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
