name: Metrics
on:
  schedule:
    - cron: "0 * * * *" # Cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AbyZerimar11
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          repositories: 100
          achievements: yes
          code: yes
          isocalendar: yes
